name: Test Secrets
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: |
          echo "PAT length: ${#REPO_PAT}"
          echo "Polygon Key length: ${#POLYGON_API_KEY}"
        env:
          REPO_PAT: ${{ secrets.REPO_PAT }}
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}

