name: Test Secrets
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: |
          echo "PAT length: ${#GITHUB_PAT}"
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

